package com.ecps.model;

import com.ecps.model.base.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

@ApiModel(value="分类",description="数据库表：tb_content")
@Table(name = "tb_content")
public class TbContent extends BaseModel{

    @ApiModelProperty(value="",name="id", required=true)
    @NotEmpty
    @Id
    @Column(name = "id")
    private Long id;

    @ApiModelProperty(value="内容类目ID",name="categoryId", required=true)
    @NotEmpty
    @Column(name = "category_id")
    private Long categoryId;

    @ApiModelProperty(value="内容标题",name="title")
    @Column(name = "title")
    private String title;

    @ApiModelProperty(value="子标题",name="subTitle")
    @Column(name = "sub_title")
    private String subTitle;

    @ApiModelProperty(value="标题描述",name="titleDesc")
    @Column(name = "title_desc")
    private String titleDesc;

    @ApiModelProperty(value="链接",name="url")
    @Column(name = "url")
    private String url;

    @ApiModelProperty(value="图片绝对路径",name="pic")
    @Column(name = "pic")
    private String pic;

    @ApiModelProperty(value="图片2",name="pic2")
    @Column(name = "pic2")
    private String pic2;

    @ApiModelProperty(value="内容",name="content")
    @Column(name = "content")
    private String content;

    /**
     * 获取  字段:tb_content.id
     *
     * @return tb_content.id, 
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置  字段:tb_content.id
     *
     * @param id the value for tb_content.id, 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取 内容类目ID 字段:tb_content.category_id
     *
     * @return tb_content.category_id, 内容类目ID
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * 设置 内容类目ID 字段:tb_content.category_id
     *
     * @param categoryId the value for tb_content.category_id, 内容类目ID
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * 获取 内容标题 字段:tb_content.title
     *
     * @return tb_content.title, 内容标题
     */
    public String getTitle() {
        return title;
    }

    /**
     * 设置 内容标题 字段:tb_content.title
     *
     * @param title the value for tb_content.title, 内容标题
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * 获取 子标题 字段:tb_content.sub_title
     *
     * @return tb_content.sub_title, 子标题
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * 设置 子标题 字段:tb_content.sub_title
     *
     * @param subTitle the value for tb_content.sub_title, 子标题
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle == null ? null : subTitle.trim();
    }

    /**
     * 获取 标题描述 字段:tb_content.title_desc
     *
     * @return tb_content.title_desc, 标题描述
     */
    public String getTitleDesc() {
        return titleDesc;
    }

    /**
     * 设置 标题描述 字段:tb_content.title_desc
     *
     * @param titleDesc the value for tb_content.title_desc, 标题描述
     */
    public void setTitleDesc(String titleDesc) {
        this.titleDesc = titleDesc == null ? null : titleDesc.trim();
    }

    /**
     * 获取 链接 字段:tb_content.url
     *
     * @return tb_content.url, 链接
     */
    public String getUrl() {
        return url;
    }

    /**
     * 设置 链接 字段:tb_content.url
     *
     * @param url the value for tb_content.url, 链接
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * 获取 图片绝对路径 字段:tb_content.pic
     *
     * @return tb_content.pic, 图片绝对路径
     */
    public String getPic() {
        return pic;
    }

    /**
     * 设置 图片绝对路径 字段:tb_content.pic
     *
     * @param pic the value for tb_content.pic, 图片绝对路径
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * 获取 图片2 字段:tb_content.pic2
     *
     * @return tb_content.pic2, 图片2
     */
    public String getPic2() {
        return pic2;
    }

    /**
     * 设置 图片2 字段:tb_content.pic2
     *
     * @param pic2 the value for tb_content.pic2, 图片2
     */
    public void setPic2(String pic2) {
        this.pic2 = pic2 == null ? null : pic2.trim();
    }

    /**
     * 获取 内容 字段:tb_content.content
     *
     * @return tb_content.content, 内容
     */
    public String getContent() {
        return content;
    }

    /**
     * 设置 内容 字段:tb_content.content
     *
     * @param content the value for tb_content.content, 内容
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_content
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", title=").append(title);
        sb.append(", subTitle=").append(subTitle);
        sb.append(", titleDesc=").append(titleDesc);
        sb.append(", url=").append(url);
        sb.append(", pic=").append(pic);
        sb.append(", pic2=").append(pic2);
        sb.append(", created=").append(super.created);
        sb.append(", updated=").append(super.updated);
        sb.append(", content=").append(content);
        sb.append("]");
        return sb.toString();
    }
}