package com.ecps.model;

import com.ecps.model.base.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

@ApiModel(value="商品规则参数",description="数据库表：tb_item_param")
@Table(name = "tb_item_param")
public class TbItemParam extends BaseModel{

    @ApiModelProperty(value="",name="id", required=true)
    @NotEmpty
    @Id
    @Column(name = "id")
    private Long id;

    @ApiModelProperty(value="商品类目ID",name="itemCatId")
    @Column(name = "item_cat_id")
    private Long itemCatId;

    @ApiModelProperty(value="参数数据，格式为json格式",name="paramData")
    @Column(name = "param_data")
    private String paramData;

    /**
     * 获取  字段:tb_item_param.id
     *
     * @return tb_item_param.id, 
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置  字段:tb_item_param.id
     *
     * @param id the value for tb_item_param.id, 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取 商品类目ID 字段:tb_item_param.item_cat_id
     *
     * @return tb_item_param.item_cat_id, 商品类目ID
     */
    public Long getItemCatId() {
        return itemCatId;
    }

    /**
     * 设置 商品类目ID 字段:tb_item_param.item_cat_id
     *
     * @param itemCatId the value for tb_item_param.item_cat_id, 商品类目ID
     */
    public void setItemCatId(Long itemCatId) {
        this.itemCatId = itemCatId;
    }

    /**
     * 获取 参数数据，格式为json格式 字段:tb_item_param.param_data
     *
     * @return tb_item_param.param_data, 参数数据，格式为json格式
     */
    public String getParamData() {
        return paramData;
    }

    /**
     * 设置 参数数据，格式为json格式 字段:tb_item_param.param_data
     *
     * @param paramData the value for tb_item_param.param_data, 参数数据，格式为json格式
     */
    public void setParamData(String paramData) {
        this.paramData = paramData == null ? null : paramData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", itemCatId=").append(itemCatId);
        sb.append(", created=").append(created);
        sb.append(", updated=").append(updated);
        sb.append(", paramData=").append(paramData);
        sb.append("]");
        return sb.toString();
    }
}