package com.ecps.model;

import com.ecps.model.base.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;

@ApiModel(value="商品规格和商品的关系表",description="数据库表：tb_item_param_item")
@Table(name = "tb_item_param_item")
public class TbItemParamItem extends BaseModel{

    @ApiModelProperty(value="",name="id", required=true)
    @NotEmpty
    @Id
    @Column(name = "id")
    private Long id;

    @ApiModelProperty(value="商品ID",name="itemId")
    @Column(name = "item_id")
    private Long itemId;

    @ApiModelProperty(value="参数数据，格式为json格式",name="paramData")
    @Column(name = "param_data")
    private String paramData;

    /**
     * 获取  字段:tb_item_param_item.id
     *
     * @return tb_item_param_item.id, 
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置  字段:tb_item_param_item.id
     *
     * @param id the value for tb_item_param_item.id, 
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取 商品ID 字段:tb_item_param_item.item_id
     *
     * @return tb_item_param_item.item_id, 商品ID
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * 设置 商品ID 字段:tb_item_param_item.item_id
     *
     * @param itemId the value for tb_item_param_item.item_id, 商品ID
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * 获取 参数数据，格式为json格式 字段:tb_item_param_item.param_data
     *
     * @return tb_item_param_item.param_data, 参数数据，格式为json格式
     */
    public String getParamData() {
        return paramData;
    }

    /**
     * 设置 参数数据，格式为json格式 字段:tb_item_param_item.param_data
     *
     * @param paramData the value for tb_item_param_item.param_data, 参数数据，格式为json格式
     */
    public void setParamData(String paramData) {
        this.paramData = paramData == null ? null : paramData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param_item
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", itemId=").append(itemId);
        sb.append(", created=").append(created);
        sb.append(", updated=").append(updated);
        sb.append(", paramData=").append(paramData);
        sb.append("]");
        return sb.toString();
    }
}